# -*- coding: utf-8 -*-
"""HeartDisease.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eEJ4fAEoUBNIwpTGKWgE9r89ExpWFllR
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

h=pd.read_csv("heart_2020_cleaned.csv")
#h.head()

h2=h.copy()

h2=h2.drop(['KidneyDisease','SkinCancer','PhysicalHealth','SleepTime'],axis=1)
#h2.head()

h2.dropna(inplace=True)
#h2.isnull().sum()

#h2.info()

col=['PhysicalActivity','Diabetic','Sex','DiffWalking','Asthma','Stroke','AlcoholDrinking','Smoking','HeartDisease','Race','GenHealth']
le=LabelEncoder()
h2[col] = h2[col].apply(le.fit_transform)

#h2.head()

h2['AgeCategory'] = h2['AgeCategory'].replace(['80 or older'],'80-95')

l=h2.AgeCategory.str.split('-').str[0].tolist()
m=h2.AgeCategory.str.split('-').str[1].tolist()

o=[(int(g) + int(h)) / 2 for g, h in zip(l, m)]

h2['AgeCategory']=o
#h2.head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

h3=h2.copy()

x=h3.drop('HeartDisease',axis=1)
y=h3['HeartDisease']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

lg = LogisticRegression(max_iter=3000)
lg.fit(x_train,y_train)

#p=model.predict(x_test)


import pickle

pickle.dump(lg, open('model.pkl', 'wb'))
model = pickle.load(open('model.pkl', 'rb'))
